### ISSUE TITLE
[Bug]: UI has weird buttons I can't see.

### ISSUE THREAD

**Issue by ninjasaid2k** [anapnoe/stable-diffusion-webui-ux#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I installed this extension but I am not able to scroll to the right to see some buttons.
![thggsd](https://user-images.githubusercontent.com/99513716/226473649-d11e46a7-d6a7-4e44-b5a9-f0f0dffe995a.PNG)

### Steps to reproduce the problem

1. have extension
2. cant see button.

### What should have happened?

I should be able to see the buttons like the settings button.

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--autolaunch --xformers --api --cors-allow-origins=*
call webui.bat
```

### List of extensions

Controlnet

### Console logs

```Shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\Users\****(*\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 120, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\*****\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__    await responder(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\Users\*****\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 338, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path C:\Users\*****\stable-diffusion-webui\html\svg\picture-in-picture-exit-line.svg does not exist.
```

### Additional information

anything.

**Comment by ninjasaid2k** [comment]
I got rid of the error message but I still don't get the UI in this sub

![fegeegew](https://user-images.githubusercontent.com/99513716/226488529-fa1d0065-9c28-4724-873c-729bc86c91a9.PNG)

**Comment by ninjasaid2k** [comment]
I installed it directly into the extensions rather than the webui, my bad.
