### ISSUE TITLE
[Bug]: New Error since 079a5e4d

### ISSUE THREAD

**Issue by Skuwwy** [anapnoe/stable-diffusion-webui-ux#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hi, there is a new error appearing on console any time I generate an image. It doesn't seem to stop the process or affect the generation though.

```
Error running process_batch: D:\SD - Anapnoe\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\\stable-diffusion-webui-ux\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'
```

### Steps to reproduce the problem

1. Press Generate
2. Look at console

### What should have happened?

There should be no errors

### Commit where the problem happens

079a5e4d

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--medvram --opt-sdp-attention --opt-split-attention --no-download-sd-model --api --autolaunch --xformers
```

### List of extensions

<html><body>

multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git
-- | --

</body>
</html>

### Console logs

```Shell
venv "D:\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 079a5e4d8c8a3a4de43f75a7f64a8f363d02a8c1
Installing requirements for Web UI
Installing sd-webui-controlnet requirement: mediapipe==0.9.1.0
Installing sd-webui-controlnet requirement: opencv-python

Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Launching Web UI with arguments: --medvram --opt-sdp-attention --opt-split-attention --no-download-sd-model --api --autolaunch --xformers
D:\stable-diffusion-webui-ux\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Loading weights [2d05a41142] from D:\stable-diffusion-webui-ux\models\Stable-diffusion\perpetualDiffusion10_v10Moon.safetensors
Creating model from config: D:\stable-diffusion-webui-ux\models\Stable-diffusion\perpetualDiffusion10_v10Moon.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(10): 21charturnerv2, 3drenderstructure_neg, DrD_PNTE768, HyperSmoke, nartfixer, Neg_Facelift768, nfixer, nrealfixer, photorealism_neg, rzminjourney
Textual inversion embeddings skipped(15): advntr, bad-hands-5, badprompt, bad_prompt_version2, bybadartistsnegative, easynegative, magicalinterior, NebulaMagicNegative, NebulaMagicPositive, ng_deepnegative_v1_75t, realisticvision-negative-embedding, SouthOfTheBorderSD15, style-empire, style-sylvamagic, Unspeakable-Horrors-24v
Model loaded in 5.4s (load weights from disk: 0.2s, create model: 0.2s, apply weights to model: 1.5s, apply half(): 0.9s, move model to device: 0.4s, load textual inversion embeddings: 2.3s).
Error calling: D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-ux\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error calling: D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py/ui
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-ux\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py", line 94, in ui
    presets = loadpresets(filepath)
  File "D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py", line 539, in loadpresets
    presets = json.load(f)
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 17.3s (import torch: 2.2s, import gradio: 1.3s, import ldm: 0.7s, other imports: 1.3s, list SD models: 0.2s, setup codeformer: 0.1s, load scripts: 3.7s, load SD checkpoint: 5.7s, create ui: 1.4s, gradio launch: 0.2s, scripts app_started_callback: 0.4s).
Error running process: D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-ux\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Error running process_batch: D:\stable-diffusion-webui-ux\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-ux\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:15<00:00,  1.31it/s]
[Tiled VAE]: input_size: torch.Size([1, 4, 112, 128]), tile_size: 64, padding: 11██████| 20/20 [00:10<00:00,  1.87it/s]
[Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 64x64, original tile size 64x64
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 64 x 56 image
[Tiled VAE]: Executing Decoder Task Queue: 100%|████████████████████████████████████| 492/492 [00:00<00:00, 563.39it/s]
[Tiled VAE]: Done in 1.587s, max VRAM alloc 1894.458 MB
```

**Comment by anapnoe** [comment]
try to update your extension sd-webui-regional-prompter the error seems to be from the extension

**Comment by rushuna86** [comment]
@anapnoe maybe put up a notice for people to wait for extensions to be updated and not report it as a bug to keep you from getting spammed with bugs that arent WebUIX related but extension related. Had a few extensions I've seen broken already Additional Network XYZ plot is broken and DataSet Editor also broken need to wait for extensions to be updated.
