### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gunnerdoyle** [anapnoe/stable-diffusion-webui-ux#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Since the automatic update this morning, I am getting an error whenever I try to upscale from the Extras tab

TypeError: argument of type 'NoneType' is not iterable

### Steps to reproduce the problem

Go to extras, try to upscale with any upscaler other than nearest.

### What should have happened?

The image should upscale x4

### Commit where the problem happens

 commit: 72cd27a1  •  checkpoint: 9aba26abdf

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
Already up to date.
venv "C:\Users\gunne\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 72cd27a13587c9579942577e9e3880778be195f6
Installing requirements
Installing requirements for Batch Face Swap

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1+cu113.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Loading weights [9aba26abdf] from C:\Users\gunne\stable-diffusion-webui\models\Stable-diffusion\deliberate_v2.safetensors
Creating model from config: C:\Users\gunne\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 2.8s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.6s, move model to device: 0.5s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.0s (import torch: 1.0s, import gradio: 0.7s, import ldm: 0.4s, other imports: 0.6s, load scripts: 0.7s, load SD checkpoint: 2.9s, create ui: 0.5s, gradio launch: 0.2s).
Error verifying pickled file from C:\Users\gunne\stable-diffusion-webui\models\RealESRGAN\RealESRGAN_x4plus.pth:
Traceback (most recent call last):
  File "C:\Users\gunne\stable-diffusion-webui\modules\safe.py", line 132, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\Users\gunne\stable-diffusion-webui\modules\safe.py", line 90, in check_pt
    unpickler.load()
  File "C:\Users\gunne\stable-diffusion-webui\modules\safe.py", line 27, in persistent_load
    return TypedStorage(_internal=True)
TypeError: _TypedStorage.__new__() got an unexpected keyword argument '_internal'


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=720x360 at 0x1D47FB0A440>, None, '', '', True, 0, 4, 512, 512, True, 'R-ESRGAN 4x+', 'None', 0, 0, 0, 0) {}
Traceback (most recent call last):
  File "C:\Users\gunne\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\gunne\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\gunne\stable-diffusion-webui\modules\postprocessing.py", line 61, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Users\gunne\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Users\gunne\stable-diffusion-webui\scripts\postprocessing_upscale.py", line 100, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "C:\Users\gunne\stable-diffusion-webui\scripts\postprocessing_upscale.py", line 70, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "C:\Users\gunne\stable-diffusion-webui\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Users\gunne\stable-diffusion-webui\modules\realesrgan_model.py", line 53, in do_upscale
    upsampler = RealESRGANer(
  File "C:\Users\gunne\stable-diffusion-webui\venv\lib\site-packages\realesrgan\utils.py", line 66, in __init__
    if 'params_ema' in loadnet:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by anapnoe** [comment]
how this applies to the ui-ux did you follow the instructions to install it?
