### ISSUE TITLE
[Bug]: Unable to Start WebUIX

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Getting Following Error when launching WebUI.

### Steps to reproduce the problem

Launch webui-user.bat

### What should have happened?

WebUIX Should Start.

### Commit where the problem happens

1e614d2

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --autolaunch
```

### List of extensions

Build In. Clean Clone and Install

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\SD\WebUIX\launch.py", line 370, in <module>
    start()
  File "D:\SD\WebUIX\launch.py", line 365, in start
    webui.webui()
  File "D:\SD\WebUIX\webui.py", line 295, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\SD\WebUIX\modules\ui.py", line 1627, in create_ui
    quicksettings_names = opts.quicksettings_list
  File "D:\SD\WebUIX\modules\shared.py", line 521, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'quicksettings_list'
Press any key to continue . . .
```

### Additional information

This error was from a clean install. Running from Previous Install got an error saying the config.json, sd_checkpoint, and sd_vae error and said to delete or fix it. After deleting it I get this error instead.

Traceback (most recent call last):
  File "D:\SD\WebUIX\launch.py", line 370, in <module>
    start()
  File "D:\SD\WebUIX\launch.py", line 365, in start
    webui.webui()
  File "D:\SD\WebUIX\webui.py", line 295, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\SD\WebUIX\modules\ui.py", line 1660, in create_ui
    component = create_setting_component(k, elem_id)
  File "D:\SD\WebUIX\modules\ui.py", line 1551, in create_setting_component
    raise Exception(f'bad options item type: {t} for key {key}')
Exception: bad options item type: <class 'list'> for key quicksettings
Press any key to continue . . .

**Comment by anapnoe** [comment]
yes rename the list i will fix it just notice

**Comment by anapnoe** [comment]
fixed
