### ISSUE TITLE
[Bug]: Can't See Checked Extensions

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After updating the UI, I can no longer see which extensions I have checked or unchecked. I haven't changed anything, extension-wise or settings-wise since before the update, so I believe the update is what's causing this for me.

Moreover, clicking a box shows no change. All of my extensions are enabled as well, so the box itself is simply failing to show the right state. 

![Screenshot 2023-06-13 180537](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/931371c5-6233-4b2d-92ca-d81d03337392)

### Steps to reproduce the problem

1. Go to Extensions
2. See Extension Boxes Are All Empty

### What should have happened?

1. Go to Extensions
2. See Which Extensions Are Checked or Unchecked

### Version or Commit where the problem happens

v1.3.2

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### Cross attention optimization

xformers

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae --api --autolaunch
```

### List of extensions

Shown in above image.

### Console logs

```Shell
venv "C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2-RC-511-g355c0efe
Commit hash: 355c0efed9f185d0f2259aa845e201ca44b53d49
Installing requirements
Requirement already satisfied: send2trash~=1.8 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (1.8.2)
Requirement already satisfied: dynamicprompts[attentiongrabber,magicprompt]~=0.27.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (0.27.0)
Requirement already satisfied: jinja2~=3.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.2)
Requirement already satisfied: pyparsing~=3.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.0.9)
Requirement already satisfied: transformers[torch]~=4.19 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from jinja2~=3.1->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.1.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.65.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.13.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (6.0)
Requirement already satisfied: filelock in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.12.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.5)
Requirement already satisfied: requests in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.31.0)
Requirement already satisfied: numpy>=1.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.23.5)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.15.1)
Requirement already satisfied: packaging>=20.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (23.1)
Requirement already satisfied: torch!=1.12.0,>=1.7 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.0.1+cu118)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.6.2)
Requirement already satisfied: fsspec in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.0)
Requirement already satisfied: networkx in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1)
Requirement already satisfied: sympy in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.12)
Requirement already satisfied: colorama in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from tqdm>=4.27->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.26.16)
Requirement already satisfied: mpmath>=0.19 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from sympy->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.3.0)
sd-dynamic-prompts installer: running 'C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\python.exe' -m pip install 'send2trash~=1.8' 'dynamicprompts[attentiongrabber,magicprompt]~=0.27.0'




Launching Web UI with arguments: --xformers --no-half-vae --api --autolaunch
=================================================================================
You are running xformers 0.0.17.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\silve\Documents\AI Art\__SDUX\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
2023-06-13 16:41:40,683 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-controlnet\annotator\downloads
2023-06-13 16:41:40,840 - ControlNet - INFO - ControlNet v1.1.224
Installing Layer Divider Extension: Installing  segment-anything
Installing Layer Divider Extension: Installing  opencv-python
Installing Layer Divider Extension: Installing  pytoshop==1.1.0
Loading weights [f973437a47] from C:\Users\silve\Documents\AI Art\__SDUX\models\Stable-diffusion\__Anime\_Custom\QRB2AGHIB.safetensors
Creating model from config: C:\Users\silve\Documents\AI Art\__SDUX\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\silve\Documents\AI Art\__SDUX\models\VAE\AnythingV3-pruned.vae.pt
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(7): bad-artist, bad-artist-anime, bad-hands-5, CharTurner, CharTurner2, EasyNegative, PlanIt
Model loaded in 14.2s (load weights from disk: 1.4s, create model: 0.7s, apply weights to model: 8.1s, apply half(): 1.9s, load VAE: 0.9s, move model to device: 0.9s, calculate empty prompt: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 40.4s (import torch: 5.2s, import gradio: 4.8s, import ldm: 1.6s, other imports: 4.2s, setup codeformer: 0.3s, list SD models: 0.2s, load scripts: 8.8s, scripts before_ui_callback: 0.5s, create ui: 14.4s, gradio launch: 0.4s).
preload_extensions_git_metadata for 21 extensions took 2.97s
                                  *** Error running before_process: C:\Users\silve\Documents\AI Art\__SDUX\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable
```

**Comment by rushuna86** [comment]
i can confirm i get this issue, and also getting the same error at the bottom everytime an image is generated in t2i with additional network loras

**Comment by heroofthebeach** [comment]
I'm experiencing this too and you can _technically_ tell when a box is checked or not, as the white box grows ever so slightly when a box is checked, and everything still functions properly otherwise. It's just a style problem, albeit a significant one.,
