### ISSUE TITLE
[Bug]: AsyncConnectionPool

### ISSUE THREAD

**Issue by offmybach** [anapnoe/stable-diffusion-webui-ux#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

  Keep getting this error when trying to load.  this is a clean install of win11 pro and should have no conflicts. Python 3.10.6, Pytorch 2.0.1., and Cuda 11.8. Have no other SD installs. I was gonna give your new work a try first before using A1111 and comfy.

 from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>
    from gradio import utils
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\utils.py", line 353, in <module>
    class AsyncRequest:
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
Press any key to continue . . .

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
run the bat file

### What should have happened?

app loaded 

### Sysinfo

i dont know how to do this?  please message  back if need it. im a novice when it comes to code.

### Console logs

```Shell
venv "C:\Users\mdmen\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 9e3ef7b2a8161139bfda18ff57929e3e40fcb580
Installing xformers
Launching Web UI with arguments: --allow-code --xformers --skip-torch-cuda-test --no-half-vae --api --ckpt-dir A:\stable-diffusion-checkpoints
Traceback (most recent call last):
  File "C:\Users\mdmen\stable-diffusion-webui-ux\launch.py", line 48, in <module>
    main()
  File "C:\Users\mdmen\stable-diffusion-webui-ux\launch.py", line 44, in main
    start()
  File "C:\Users\mdmen\stable-diffusion-webui-ux\modules\launch_utils.py", line 432, in start
    import webui
  File "C:\Users\mdmen\stable-diffusion-webui-ux\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\mdmen\stable-diffusion-webui-ux\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>
    from gradio import utils
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\utils.py", line 353, in <module>
    class AsyncRequest:
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "C:\Users\mdmen\stable-diffusion-webui-ux\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
Press any key to continue . . .
```

**Comment by anapnoe** [comment]
issue seems that has been fixed reinstall latest commit and if everything is ok close the issue 
best regards
