### ISSUE TITLE
[Bug]: Endless load

### ISSUE THREAD

**Issue by Dajova** [anapnoe/stable-diffusion-webui-ux#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to start up the program, only to be met with a *almost* endless loading screen. Results from checking task manager indicates that it's trying to read something, but doesn't say what and just gets stuck in limbo.

![Screenshot 2023-12-10 141045](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/27521654/c8a95597-fa18-4a62-896e-75858c9ddf6d)
![Screenshot 2023-12-10 140224](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/27521654/fa8deba9-4694-4965-8860-8bebe29290a1)
![Screenshot 2023-12-10 214911](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/27521654/aee33e9e-af5b-4128-bc04-e82f156eb635)
![Screenshot 2023-12-10 215656](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/27521654/df54fbf7-738e-4f2a-bfdb-3182b7991db2)

### Steps to reproduce the problem

1. Start up SD. Starts fine.
2. Download and install Deforum/AnimateDiff/ControlNet.
3. Exit UI and close down python.
4. Start it up again.
5. Stuck with the screenshots above.

### What should have happened?

It should have started up the program within 1 min, but after 20m+, still on the same screen. It stops at loading Deforum, so i'm not sure if it's because of that or some interaction between the new version that is incompatible somewhere... Only started happening today (was fine yesterday and a few times today). Only seems to happen sometimes, not sure what the cause is, but it always starts with Deforum.

### Sysinfo

-

### What browsers do you use to access the UI ?

Mozilla Firefox

### Console logs

```Shell
-
```

### Additional information

The only note that i can think of is that it starts reading the disk >200mb/s after ControlNet is loaded. But it always stops doing anything else after the screenshot above.

edit: seems to be related to this specific model, for some reason. changing the model seems to have fixed the issue. which is weird, since i've used this model for weeks without issues until today...

![Screenshot 2023-12-10 232927](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/27521654/3d18a8c1-6c7b-41ae-8117-ebdbca4c2f6d)

Also, decommiting this thread shown above seems to fix the endless loading loop, even tho it says that it still cant exit the process...

edit2: Nwm, after further testing and changing the config to use another model and it still happens rules out specific model usage. And removing all the extensions also rule out any outside factors, it just started happening for no reason today, so no idea what just changed, cus nothing has changed from yesterday.

At least with no extensions, i was able to actually launch the UI again, but with a error attached to it, at least. (before it crashed)

```
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\dajov\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dajov\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\dajov\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\dajov\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "D:\stable-diffusion-webui\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\stable-diffusion-webui\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1968, in launch
    and not networking.url_ok(self.local_url)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)
```

After trying to enter the UI again, i get this error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "C:\Users\dajov\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```
... and after launching it again, it work *mostly* fine again. So something is definitly up and will most probably happen again.

**Comment by Dajova** [comment]
It's stopped doing it now, so i'm guessing there was just a bad update somewhere. I'll re-open the issue if it happens again. Not sure what happened or what caused it, regardless.

**Comment by Dajova** [comment]
nwm, it's started happening again after i rebooted the computer. it's like its trying to cache everything at once and that takes 20m+, but once it's done caching everything, it takes less than 20 sec to start it up again. Is this intended?

**Comment by anapnoe** [comment]
Doesn't seem to be related to the ui-ux
