### ISSUE TITLE
[Bug]: Page does not load on iPad

### ISSUE THREAD

**Issue by halr9000** [anapnoe/stable-diffusion-webui-ux#226]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Main interface will not load at all on iPad. Most times I will see only the "Stable Diffusion" window title, and a blank screen, and page load will stop. (Stop button changes to refresh.) Occasionally, with multiple refresh attempts and after a very long delay (>60s ? So long, it's not worth timing), the SDUX loading screen text will appear, but never progresses past that.

I've had it load from this same device previously, but I had not been running SDUX for some months, so I do not know what may have changed. Suspect it's Gradio, but this is very hard to troubleshoot from mobile device without access to js console. Happy to help troubleshoot though if you have some tricks.

Works fine from multiple PCs, Macs, and Android devices in my possession.

### Steps to reproduce the problem

1. Fresh install
2. Start WebUI
3. Load page from PC: success
4. Load page from Android: success
5. Load page from iPad Safari: fail
6. Load page from iPad Chrome: fail

### What should have happened?

All the things

### What browsers do you use to access the UI ?

Google Chrome, Brave, Apple Safari, Android, iOS

### Sysinfo

[sysinfo-2024-04-06-15-48.json](https://github.com/anapnoe/stable-diffusion-webui-ux/files/14894073/sysinfo-2024-04-06-15-48.json)

### Console logs

```Shell
[Note that this output is not from a fresh install, but I have reproduced many times. Definitely some crap in here.]

fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\sd-webui-infinite-image-browsing\install.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --server-name 0.0.0.0 --xformers --api --skip-python-version-check --no-download-sd-model --enable-insecure-extension-access --civsfz-api-key 5d7513b761e1f8b47258a3da62a26f66
reading lora D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_2step_lora.safetensors: AssertionError
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_2step_lora.safetensors is not a safetensors file

reading lora D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_8step_lora.safetensors: AssertionError
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_8step_lora.safetensors is not a safetensors file

CHv1.8.3: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Loading weights [15012c538f] from D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Stable-diffusion\sd15\realisticVisionV51_v51VAE.safetensors
Creating model from config: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\configs\v1-inference.yaml
CHv1.8.3: Set Proxy: 
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\model_preset_manager\scripts\main.py:446: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  with gr.Column(min_width=100, scale = 0.1):
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\model_preset_manager\scripts\main.py:463: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  model_generation_data = gr.Textbox(label = model_generation_data_label_text(), value = "", lines = 3, elem_id = "def_model_gen_data_textbox").style(show_copy_button=True)
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\model_preset_manager\scripts\main.py:466: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  triggerWords = gr.CheckboxGroup([], multiselect=True, label="Trigger Words", interactive = True).style(container=True, item_container=True)
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\model_preset_manager\scripts\main.py:466: GradioDeprecationWarning: The `item_container` parameter is deprecated.
  triggerWords = gr.CheckboxGroup([], multiselect=True, label="Trigger Words", interactive = True).style(container=True, item_container=True)
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions\model_preset_manager\scripts\main.py:493: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_textbox = gr.Textbox(interactive=False, label="Output").style(show_copy_button=True)
D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
Applying attention optimization: xformers... done.
Running on local URL:  http://0.0.0.0:7860
Model loaded in 10.7s (load weights from disk: 0.2s, create model: 0.9s, apply weights to model: 7.8s, load textual inversion embeddings: 1.0s, calculate empty prompt: 0.5s).

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
Startup time: 51.8s (prepare environment: 8.1s, import torch: 9.3s, import gradio: 4.2s, setup paths: 6.1s, initialize shared: 0.5s, other imports: 2.7s, list SD models: 0.4s, load scripts: 5.7s, create ui: 9.9s, gradio launch: 4.4s, add APIs: 0.5s).
```

**Comment by halr9000** [comment]
Interesting! Running with disabling all extensions actually reverts the UI to upstream, which surprised me, and the page loads fine:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/1eec46a8-0bea-4e66-a472-bdf6f1fb80f7)

Console:

```
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
Launching Web UI with arguments: --server-name 0.0.0.0 --xformers --api --skip-python-version-check --no-download-sd-model --disable-all-extensions
*** "--disable-all-extensions" arg was used, will not load any extensions ***
Loading weights [15012c538f] from D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Stable-diffusion\sd15\realisticVisionV51_v51VAE.safetensors
Creating model from config: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860
Applying attention optimization: xformers... done.
Model loaded in 2.6s (load weights from disk: 0.1s, create model: 0.7s, apply weights to model: 1.5s, calculate empty prompt: 0.1s).

To create a public link, set `share=True` in `launch()`.
Startup time: 17.9s (prepare environment: 2.8s, import torch: 4.8s, import gradio: 1.4s, setup paths: 1.4s, initialize shared: 0.3s, other imports: 0.8s, list SD models: 0.1s, load scripts: 1.2s, create ui: 0.6s, gradio launch: 4.4s, add APIs: 0.2s).
100%|██████████| 20/20 [00:03<00:00,  6.07it/s]
Total progress: 100%|██████████| 20/20 [00:02<00:00,  7.01it/s]s]
```

Will test a few more variations.

**Comment by halr9000** [comment]
Here it is with only extra (not built-in) extensions, and it is broken as I expected:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/16bad55d-aa58-4ecb-81af-c3d8f5f12432)

Console:
```
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
Launching Web UI with arguments: --server-name 0.0.0.0 --xformers --api --skip-python-version-check --no-download-sd-model --disable-extra-extensions
*** "--disable-extra-extensions" arg was used, will only load built-in extensions ***
reading lora D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_2step_lora.safetensors: AssertionError
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_2step_lora.safetensors is not a safetensors file

reading lora D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_8step_lora.safetensors: AssertionError
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 38, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\cache.py", line 114, in cached_data_for_file
    value = func()
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\extensions-builtin\Lora\network.py", line 31, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\modules\sd_models.py", line 283, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Lora\sdxl_lightning_8step_lora.safetensors is not a safetensors file

Loading weights [15012c538f] from D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\models\Stable-diffusion\sd15\realisticVisionV51_v51VAE.safetensors
Creating model from config: D:\hal\stable-diffusion\StabilityMatrix\Packages\Stable Diffusion Web UI-UX\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860
Applying attention optimization: xformers... done.
Model loaded in 2.4s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 1.7s, calculate empty prompt: 0.1s).

To create a public link, set `share=True` in `launch()`.
Startup time: 18.2s (prepare environment: 2.7s, import torch: 4.6s, import gradio: 1.3s, setup paths: 1.3s, initialize shared: 0.3s, other imports: 0.8s, list SD models: 0.1s, load scripts: 1.5s, create ui: 1.2s, gradio launch: 4.2s, add APIs: 0.2s).

```

**Comment by halr9000** [comment]
Update. By disabling extra extensions, it loads -- kinda. As you see in these pics, it is not happy.

All of the extra network pages say Loading like this:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/105935db-5ccc-4f94-acde-6b6898b5eaa5)

Extensions tab also fails to load:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/45a26adf-7e2c-4beb-be51-c9389d496b87)

**Comment by halr9000** [comment]
Last update for now, here's the same server with same config as above (disabled extra extensions), working just fine from Android, which is what confuses me so much.

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/a5c47230-6cf3-4207-b4a3-5717534acff7)
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/392b420b-b50e-48c4-ad59-59e25baab4cb)
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/c77e47a4-c63c-4227-ba4a-4a9f5597f05e)
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/3e010fad-af5d-4596-a76a-e6ff1ebedd4f)

**Comment by anapnoe** [comment]
Thank you for your feedback. Unfortunately, I do not have any Apple devices to test. There is an advanced selector that you can check if your current browser supports at https://caniuse.com/css-has.
