### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bryanray** [anapnoe/stable-diffusion-webui-ux#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 2ac62ce241396939c387a221e20b0a7a8c399b6f
Fetching updates for BLIP...
Checking out commit for BLIP with hash: 48211a1594f1321b00f14c9f7a5b4813144b2fb9...
Traceback (most recent call last):
  File "Z:\z\sd-ux\ux\launch.py", line 380, in <module>
    prepare_environment()
  File "Z:\z\sd-ux\ux\launch.py", line 319, in prepare_environment
    git_clone(blip_repo, repo_dir('BLIP'), "BLIP", blip_commit_hash)
  File "Z:\z\sd-ux\ux\launch.py", line 164, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "Z:\z\sd-ux\ux\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 48211a1594f1321b00f14c9f7a5b4813144b2fb9 for BLIP.
Command: "git" -C "Z:\z\sd-ux\ux\repositories\BLIP" checkout 48211a1594f1321b00f14c9f7a5b4813144b2fb9
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: 48211a1594f1321b00f14c9f7a5b4813144b2fb9

Press any key to continue . . .

### Steps to reproduce the problem

a

### What should have happened?

a

### Commit where the problem happens

a

### Command Line Arguments

```Shell
a
```

### List of extensions

a

### Console logs

```Shell
a
```

**Comment by bryanray** [comment]
deleted
