### ISSUE TITLE
[Bug]:  WebUi Supermerger

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

New mode for merging checkpoint in Supermerger.

CosineA and CosineB and Smooth works.

Tensor mode throws up errors.

### Steps to reproduce the problem

1. Go to .... Supermerger
2. Press .... Select Merge mode Tensor
3. ...Press Merge.
4. Throws up Errors

Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 307, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 375, in smerge
    talphas = int(theta_0[key].shape[0]*(current_beta))
IndexError: tuple index out of range

### What should have happened?

Generates a merge using Tensor Mode.

### Commit where the problem happens

Latest Version

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of extensions

None

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 307, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 375, in smerge
    talphas = int(theta_0[key].shape[0]*(current_beta))
IndexError: tuple index out of range
```

**Comment by rushuna86** [comment]
forgot to mention works fine in automatic1111 webui

**Comment by anapnoe** [comment]
there is no versioning system for extensions and newer extensions may not work with the stable release, commits of extensions should be before 25th of March 2023 for the stable release 
extensions updated after 25th of March should use the `dev `branch
