### ISSUE TITLE
[Bug]: Batches have memory of last position

### ISSUE THREAD

**Issue by Up-Bound** [anapnoe/stable-diffusion-webui-ux#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When you generate a batch of images you will see mulitple thumbnails on the bottom of the generation window like the photo below:
![image](https://user-images.githubusercontent.com/61359739/235114277-5214b0e8-cb43-4289-ae24-d64f54cdf905.png)

After clicking into the image to view it within a fullscreen window, then exiting out through the x button on the top-right corner. Then regardless of whatever photo you choose and fullscreen on, it will always return to the previous image that you exited on.

for example if you click on image 4's thumbnail, opened up image 4 in full-screen view, exited out of image 4 in full-screen view, clicked on image 6, opened up image 6 in fullscreen view. Image 4 comes up in fullscreen instead.

### Steps to reproduce the problem

1. Generate a batch of photos
2. select any photo's thumbnail, then open the image in a fullscreen tab by clicking it's image preview.
3. exit out of it's fullscreen view by selecting the x on the top-right corner
4. select any other batch generated thumbnail, then click on image preview.
5. the fullscreen is not on the selected image preview but instead on the previous ones.

### What should have happened?

When clicking on an image preview, the image preview selected should be fullscreened.

### Commit where the problem happens

6fbe525f7dafd63b447334b6c476c190b02da7cb

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--disable-nan-check --no-half-vae --xformers
```

### List of extensions

![image](https://user-images.githubusercontent.com/61359739/235116594-46dd8c9a-25d9-4b0d-9454-e31c3fd4be4c.png)

### Console logs

```Shell
venv "W:\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 6fbe525f7dafd63b447334b6c476c190b02da7cb
Installing requirements for Web UI


Launching Web UI with arguments: --disable-nan-check --no-half-vae --xformers
ControlNet v1.1.101
ControlNet v1.1.101
Loading weights [7f15df40ed] from W:\stable-diffusion-webui-ux\models\Stable-diffusion\cuteyukimix_v20.safetensors
Creating model from config: W:\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: W:\stable-diffusion-webui-ux\models\VAE\animevae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(2): corneo_marin_kitagawa, easynegative
Textual inversion embeddings skipped(1): 21charturnerv2
Model loaded in 5.4s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 1.0s, apply half(): 0.7s, load VAE: 0.7s, move model to device: 1.0s, load textual inversion embeddings: 1.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.6s (import torch: 1.7s, import gradio: 1.1s, import ldm: 0.7s, other imports: 1.2s, setup codeformer: 0.2s, load scripts: 1.8s, load SD checkpoint: 6.1s, create ui: 2.5s, gradio launch: 0.3s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/extra-quality-tags.csv. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/danbooru.csv. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/emb.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/hyp.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/lora.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/lyco.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/wcet.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "W:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/a1111-sd-webui-tagcomplete/tags/temp/wc.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.20s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.36s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.17s/it]
```

**Comment by anapnoe** [comment]
confirmed I will fix it thank you
